config/routes.rb
LogPile::Engine.routes.draw do
  resources :logfiles, :only do
    get 'poll', :on => :collection
  end
  
  # match '/:permalink/poll' => 'logfiles#poll', :as => 'poll'
  # match '/:permalink' => 'logfiles#show', :as => 'permalink'

  root :to => 'logfiles#index'
end

app/models/log_pile/logfile.rb
module LogPile
  class Logfile < ActiveRecord::Base
    validates_presence_of :name, :path

    after_create :generate_permalink

    def to_param
      permalink
    end

    def file_last_modified
      File.stat(path).mtime
    end

    def generate_permalink
      self.permalink = name.gsub(/\s/, '_').downcase
      save
    end
  end
end

app/controllers/log_engine/application_controller.rb
module LogEngine
  class ApplicationController < ActionController::Base
  end
end

app/controllers/log_engine/logfiles_controller.rb
module LogEngine
  class LogfilesController < ApplicationController
    def index
      @files = files
    end
    
    def show
      @file = find_file_by_key(params[:permalink])
      @key = LogStreamer.start_log_stream(@file[:name])
    end
    
    def poll    
      messages = LogStreamer.log_messages(params[:key])
      render :text => messages.join("\n")
    end
    
    private    
      def find_file_by_key(key)
        {:key => key, :name => files[key]}
      end
      
      def files
        {'app' => Rails.application.config.paths["log"].first}
      end    
  end
end

app/controllers/log_pile/application_controller.rb
module LogPile
  class ApplicationController < ActionController::Base
  end
end

app/controllers/log_pile/logfiles_controller.rb
module LogPile
  class LogfilesController < ApplicationController  
    def index
      @files = Logfile.all
    end
    
    def new
      @file = Logfile.new
    end

    def create
      @file = Logfile.new(params[:logfile])
      if(@file.save)
        redirect_to logfiles_path, :notice => "File added."
      else
        render :new
      end
    end

    def show
      @file = Logfile.find_by_permalink(params[:id])
      @key = log_streamer.start_log_stream(@file.path)
    end
    
    def poll    
      messages = log_streamer.log_messages(params[:key])
      render :text => messages.join("\n")
    end
    
    private
      def log_streamer
        LogStreamer.instance
      end    
  end
end

app/helpers/log_engine/application_helper.rb
module LogEngine
  module ApplicationHelper
  end
end

app/helpers/log_engine/logfiles_helper.rb
module LogEngine
  module LogfilesHelper
  end
end

app/helpers/log_pile/application_helper.rb
module LogPile
  module ApplicationHelper
  end
end

app/helpers/log_pile/logfiles_helper.rb
module LogPile
  module LogfilesHelper
  end
end

app/views/layouts/log_engine/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>LogEngine</title>
		<%= stylesheet_link_tag    "http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css" %>  
	  <%= stylesheet_link_tag    "log_engine/application" %>
	  <%= javascript_include_tag "log_engine/application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<div class="content">
				<%= yield %>		
			</div>
		</div>
	</body>
</html>

app/views/layouts/log_pile/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>LogPile</title>
		<%= stylesheet_link_tag    "http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css" %>  
	  <%= stylesheet_link_tag    "log_pile/application" %>
	  <%= javascript_include_tag "log_pile/application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="topbar">
      <div class="fill">
        <div class="container">
					<%= link_to "LogPile", root_path, :class => :brand %>
        </div>
      </div>
    </div>
		<div class="container">
			<div class="content">
				<%= yield %>		
			</div>
		</div>
	</body>
</html>

app/views/log_engine/logfiles/show.html.erb
<h3><%= @file[:name] %></h3>

<div class="clearfix">
	<pre id="messages" data-poller-location="<%= poll_path(:key => @key) %>"></pre>
</div>

<div class="row">
	<div id="loader" class="center hidden">
		<%= image_tag "log_engine/ajax-loader.gif" %>
	</div>
</div>

<div class="row">
	<div class="span8">
		<span class="help-block"><strong>Note:</strong>	Scroll to the bottom to automatically scroll.</span>
	</div>
	<div class="span8">
		<form class="pull-right">
			<div class="input">
				<input id="append-log-messages" type="checkbox" checked />
				<span>Append new log messages</span>
			</div>
		</form>
	</div>
</div>

app/views/log_pile/logfiles/index.html.erb
<section>
  <p class="pull-right">
    <%= link_to "Add log file", new_logfile_path, :class => :btn %>
  </p>
</section>

<section>
  <table class="bordered-table">
    <thead>
      <tr>
        <th>Path</th>
        <th>Last Modified</th>
      </tr>
    </thead>
    <tbody>
      <% @files.each do |file| %>
        <tr>
          <td>
            <%= link_to file.name, logfile_path(file) %>
          </td>
          <td>
            <%= file.file_last_modified %>
          </td>
          <td>
            Edit
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/log_pile/logfiles/new.html.erb
<div class="well">
  <%= form_for @file do |f| %>
    <fieldset>
      <legend>Add log file</legend>
      <div class="clearfix">
        <%= f.label :name %>
        <div class="input">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="clearfix">
        <%= f.label :path %>
        <div class="input">
          <%= f.text_field :path %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Add", :class => "btn primary" %>
        <%= link_to "Cancel", logfiles_path, :class => "btn" %>
      </div>
    </fieldset>
  <% end %>	
</div>

app/views/log_pile/logfiles/show.html.erb
<h3><%= @file[:name] %></h3>

<div class="clearfix">
	<pre id="messages" data-poller-location="<%= poll_logfiles_path(:key => @key) %>"></pre>
</div>

<div class="row">
	<div id="loader" class="center hidden">
		<%= image_tag "log_pile/ajax-loader.gif" %>
	</div>
</div>

<div class="row">
	<div class="span8">
		<span class="help-block"><strong>Note:</strong>	Scroll to the bottom to automatically scroll.</span>
	</div>
	<div class="span8">
		<form class="pull-right">
			<div class="input">
				<input id="append-log-messages" type="checkbox" checked />
				<span>Append new log messages</span>
			</div>
		</form>
	</div>
</div>